// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNiL626lj1kyzVxHCYShdejU8eNojvDKM',
    appId: '1:1038431752400:web:6bc0de53befcdeedf5ced5',
    messagingSenderId: '1038431752400',
    projectId: 'uaqportal-67a8e',
    authDomain: 'uaqportal-67a8e.firebaseapp.com',
    databaseURL: 'https://uaqportal-67a8e.firebaseio.com',
    storageBucket: 'uaqportal-67a8e.appspot.com',
    measurementId: 'G-HENRQ2KQNW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVazjIjvqJ0MsubQh0Gv_Ip3C4HI9xKng',
    appId: '1:1038431752400:android:4056bb40269466a4f5ced5',
    messagingSenderId: '1038431752400',
    projectId: 'uaqportal-67a8e',
    databaseURL: 'https://uaqportal-67a8e.firebaseio.com',
    storageBucket: 'uaqportal-67a8e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZQ0alPDWaDLVeX0uVhPf3Xyo1c9yx0Z8',
    appId: '1:1038431752400:ios:aa67e98e212c9f02f5ced5',
    messagingSenderId: '1038431752400',
    projectId: 'uaqportal-67a8e',
    databaseURL: 'https://uaqportal-67a8e.firebaseio.com',
    storageBucket: 'uaqportal-67a8e.appspot.com',
    androidClientId: '1038431752400-n041cvg1ovg74v50dkas0jfs28pogbrc.apps.googleusercontent.com',
    iosClientId: '1038431752400-g6hcradogmb1fl4ofuppgf91p19g9f80.apps.googleusercontent.com',
    iosBundleId: 'uae.gov.uaq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZQ0alPDWaDLVeX0uVhPf3Xyo1c9yx0Z8',
    appId: '1:1038431752400:ios:5e02e08dc4aa6efdf5ced5',
    messagingSenderId: '1038431752400',
    projectId: 'uaqportal-67a8e',
    databaseURL: 'https://uaqportal-67a8e.firebaseio.com',
    storageBucket: 'uaqportal-67a8e.appspot.com',
    androidClientId: '1038431752400-n041cvg1ovg74v50dkas0jfs28pogbrc.apps.googleusercontent.com',
    iosBundleId: 'uae.gov.uaq.RunnerTests',
  );
}
