import 'package:ithelpdesk/domain/entities/single_data_entity.dart';

const String contactNumber = "067641000";
const String contactEmail = "info@uaqgov.ae";
const String contactWhatsAppLink = "https://wa.me/971569901116";
const String ambulanceNumber = "998";
const String policeNumber = "999";
const String civilDefenseNumber = "997";
const String electricityNumber = "991";
const String waterNumber = "992";
const String servicesInListView = "LIST";
const String servicesInGridView = "GRID";
const int maxUploadFilesize = 1024 * 1024 * 5;

const mobileRegx = r'^05[0-9]{8}$';
const emailTemplatePath = 'assets/json/email_template.txt';
const requestService = 'assets/json/request_service.json';

const ibtakerUsers = ['mooza.binyeem', 'sudheer.akula', 'mohammed.kamran'];

final List<NameIDEntity> designations = [
  NameIDEntity(1, "Accountant"),
  NameIDEntity(2, "Accounting"),
  NameIDEntity(3, "Accoutant"),
  NameIDEntity(4, "Administrative"),
  NameIDEntity(5, "Administrative Affairs Human Capital"),
  NameIDEntity(6, "Administrative Assistance"),
  NameIDEntity(7, "Administrative Assistant"),
  NameIDEntity(8, "Administrative Assistant Customer Happiness"),
  NameIDEntity(9, "Administrative HR"),
  NameIDEntity(10, "Administrative Human Capital"),
  NameIDEntity(11, "Administrative Human Resource"),
  NameIDEntity(12, "Administrator assistant"),
  NameIDEntity(13, "Administrator in Inspection Dept"),
  NameIDEntity(14, "Agricultural Supervisor"),
  NameIDEntity(15, "Archaeologist"),
  NameIDEntity(16, "Architect"),
  NameIDEntity(17, "Architect Engineering"),
  NameIDEntity(18, "Architectural Draftman"),
  NameIDEntity(19, "Architectural Engineer"),
  NameIDEntity(20, "ArchitecturalEngineer"),
  NameIDEntity(21, "Archive Department Officer"),
  NameIDEntity(22, "Archive Engineering Department"),
  NameIDEntity(23, "Assistant Accountant"),
  NameIDEntity(24, "Assistant Engineer"),
  NameIDEntity(25, "Assistant Health Inspector"),
  NameIDEntity(26, "Assistant Surveyor"),
  NameIDEntity(27, "Assistant System Engineer"),
  NameIDEntity(28, "Audit Manager"),
  NameIDEntity(29, "Auditor"),
  NameIDEntity(30, "Auditor Financial"),
  NameIDEntity(31, "Building Controller"),
  NameIDEntity(32, "Building Licenses Clerk"),
  NameIDEntity(33, "Buildings Second Observer"),
  NameIDEntity(34, "Call Center"),
  NameIDEntity(35, "Cashier"),
  NameIDEntity(36, "Chairman"),
  NameIDEntity(37, "Chairman Of Finance"),
  NameIDEntity(38, "Chairman Of Municipality"),
  NameIDEntity(39, "Chemical"),
  NameIDEntity(40, "Chemical Engineer"),
  NameIDEntity(41, "Chemist"),
  NameIDEntity(42, "Chief Administrative Media Communications"),
  NameIDEntity(43, "Chief Administrative Purchasing"),
  NameIDEntity(44, "Chief Executive Customer Happiness"),
  NameIDEntity(
      45, "Chief Executive Government Excellence Quality Representative"),
  NameIDEntity(46, "Chief Executive Government Lisison"),
  NameIDEntity(47, "Chief Executive Human Capital"),
  NameIDEntity(48, "Chief Human Capital Executive"),
  NameIDEntity(49, "Chief of Administration Department"),
  NameIDEntity(50, "Civil Engineer"),
  NameIDEntity(51, "Communication Officer"),
  NameIDEntity(52, "Computer Networs Technician"),
  NameIDEntity(53, "Computer Technician Assistant"),
  NameIDEntity(54, "Conservator"),
  NameIDEntity(55, "Consumer Protection Senior Executive"),
  NameIDEntity(56, "Consumer Rights Officer"),
  NameIDEntity(57, "Contracts & Procurement Supervisor"),
  NameIDEntity(58, "Crown Prince Secretary"),
  NameIDEntity(59, "Customer Happines Employee"),
  NameIDEntity(60, "Customer Happiness"),
  NameIDEntity(61, "Customer Happiness Employee"),
  NameIDEntity(62, "Customer Happiness Executive"),
  NameIDEntity(63, "Customer Happiness Manager"),
  NameIDEntity(64, "Customer Happiness Senior Executive"),
  NameIDEntity(65, "customer service"),
  NameIDEntity(66, "Data Entery"),
  NameIDEntity(67, "Data Entry"),
  NameIDEntity(68, "Database Officer"),
  NameIDEntity(69, "Deputy General Manger"),
  NameIDEntity(70, "Deputy Manager"),
  NameIDEntity(71, "Deputy of Head of Financial Affairs"),
  NameIDEntity(72, "Deputy of Head of Licenses"),
  NameIDEntity(73, "Designer"),
  NameIDEntity(74, "Director General"),
  NameIDEntity(75, "Director of Engineering Sector"),
  NameIDEntity(76, "Director of Infrastructure Department"),
  NameIDEntity(77, "Director Of Legal Affairs Department"),
  NameIDEntity(78, "Director of Real Estate"),
  NameIDEntity(
      79, "Director of Strategic Planning and the Future/ Statistics Unit"),
  NameIDEntity(80, "Director of the Government Liaison Office"),
  NameIDEntity(
      81, "Director of Transports Section & Head of General Monitoring Sect"),
  NameIDEntity(82, "DOT NET AND ANGULAR DEVELOPER"),
  NameIDEntity(83, "E-Correspondence System Administrator"),
  NameIDEntity(84, "Electrician"),
  NameIDEntity(85, "Engineer Computer Networks"),
  NameIDEntity(86, "Engineering Draftsman"),
  NameIDEntity(87, "Environment Inspector"),
  NameIDEntity(88, "Environmental Inspector"),
  NameIDEntity(89, "Executive Customer Happiest Center"),
  NameIDEntity(90, "Executive Government Communication"),
  NameIDEntity(91, "Executive Government Relations"),
  NameIDEntity(92, "Executive Registration and Licenses"),
  NameIDEntity(93, "Executive Secretary"),
  NameIDEntity(94, "Executive Secretary | سكرتير تنفيذي"),
  NameIDEntity(95, "Executive Strategic Planning"),
  NameIDEntity(96, "Finance expert"),
  NameIDEntity(97, "Financial Consultant Oracle Databases"),
  NameIDEntity(98, "Financial Controller"),
  NameIDEntity(99, "Finical System Management supervisor"),
  NameIDEntity(100, "Food Laboratory Technician"),
  NameIDEntity(101, "Foreman"),
  NameIDEntity(102, "Foremen"),
  NameIDEntity(103, "Full Stack Developer"),
  NameIDEntity(104, "General Inspector"),
  NameIDEntity(105, "General Manager"),
  NameIDEntity(106, "General Observer"),
  NameIDEntity(107, "General Secretary of The Executive Council"),
  NameIDEntity(108, "Geographic Information Systems Specialist"),
  NameIDEntity(109, "GIS Specialist"),
  NameIDEntity(110, "Head Data Entry"),
  NameIDEntity(111, "Head of Accounts Section"),
  NameIDEntity(112, "Head of Contracts & Procurement"),
  NameIDEntity(113, "Head of Department Rent Contracts"),
  NameIDEntity(114, "Head of Designing & Engineering Supervision Dept."),
  NameIDEntity(115, "Head Of Finance"),
  NameIDEntity(116, "Head of Finanical Affairs"),
  NameIDEntity(117, "Head of Government Services Development Department"),
  NameIDEntity(118, "Head of Human Capital Department"),
  NameIDEntity(119, "Head of Human Capital Planning"),
  NameIDEntity(120, "Head of Human Capital Section"),
  NameIDEntity(121, "Head of Human Resource"),
  NameIDEntity(122, "Head of Human Resource Department"),
  NameIDEntity(123, "Head of Human Resources"),
  NameIDEntity(124, "Head of Information Systems"),
  NameIDEntity(125, "Head of Infrastructure Dept"),
  NameIDEntity(126, "Head of Inspection Section"),
  NameIDEntity(127, "Head of Insurance Department"),
  NameIDEntity(128, "Head of Investment and Observation Department"),
  NameIDEntity(129, "Head of IT Section"),
  NameIDEntity(130, "Head of Leadership and government competences Department"),
  NameIDEntity(131, "Head of Legal Affairs"),
  NameIDEntity(132, "Head of Legal Affairs Department"),
  NameIDEntity(133, "Head of Planning Section"),
  NameIDEntity(134, "Head of Policies and Strategy Department"),
  NameIDEntity(135, "Head of Projects Study"),
  NameIDEntity(136, "Head of Registration and Licenses Section"),
  NameIDEntity(137, "Head Of Road Section"),
  NameIDEntity(138, "Head of salaries Department"),
  NameIDEntity(139, "Head Of Spatial Data Section"),
  NameIDEntity(140, "Head of Strategic Planning DEPT"),
  NameIDEntity(141, "Health and food inspector"),
  NameIDEntity(142, "Health Inspector"),
  NameIDEntity(143, "Health Observation"),
  NameIDEntity(144, "Helper"),
  NameIDEntity(145, "HR"),
  NameIDEntity(146, "Human Capital Executive"),
  NameIDEntity(147, "Human Capital Officer"),
  NameIDEntity(148, "Human Resources"),
  NameIDEntity(149, "Implementation Administrative Assistant"),
  NameIDEntity(150, "Information Technology Specialist"),
  NameIDEntity(151, "Inspector"),
  NameIDEntity(152, "Inspector Health and Food"),
  NameIDEntity(153, "Insurance & Accident Official"),
  NameIDEntity(154, "Insurance Department Officer"),
  NameIDEntity(155, "IT"),
  NameIDEntity(156, "IT Support Technician"),
  NameIDEntity(157, "Legal Assistant"),
  NameIDEntity(158, "Legal consultant"),
  NameIDEntity(159, "Legal Research Assistant"),
  NameIDEntity(160, "Legal Researcher"),
  NameIDEntity(161, "Main Accountant"),
  NameIDEntity(162, "Main Archivy Coordinator"),
  NameIDEntity(163, "Manager Director"),
  NameIDEntity(164, "Marketing and Promotion Officer"),
  NameIDEntity(165, "Mobile Application Developer"),
  NameIDEntity(166, "Monitor buildings"),
  NameIDEntity(167, "Network Engineer"),
  NameIDEntity(168, "Network Security Supervisor"),
  NameIDEntity(169, "Network Technician"),
  NameIDEntity(170, "Observer"),
  NameIDEntity(171, "Office Manager To The President Of The Rulers Office"),
  NameIDEntity(172, "Operator"),
  NameIDEntity(173, "Operator Employee"),
  NameIDEntity(174, "Oracle Apps DBA"),
  NameIDEntity(175, "Oracle Techno Functional Consultant"),
  NameIDEntity(176, "Permits"),
  NameIDEntity(177, "Programmer"),
  NameIDEntity(178, "Project Coordinator"),
  NameIDEntity(179, "Protocol Officer"),
  NameIDEntity(180, "Public Relation Coordinator and Activities"),
  NameIDEntity(181, "Public Relation Officer"),
  NameIDEntity(182, "Public Relations"),
  NameIDEntity(183, "Purchases Officer"),
  NameIDEntity(184, "Reception"),
  NameIDEntity(185, "Receptionist"),
  NameIDEntity(186, "Registration and Licenses DEPT Director"),
  NameIDEntity(187, "Responsible Public Relations"),
  NameIDEntity(188, "Secretary"),
  NameIDEntity(189, "Secretary of Deputy Director"),
  NameIDEntity(190, "Senior  Accountant"),
  NameIDEntity(191, "Senior Accountant"),
  NameIDEntity(192, "Senior Dot Net Developer"),
  NameIDEntity(193, "Senior Executive Marketing and Events"),
  NameIDEntity(194, "Senior Executive Recruitment and Selection"),
  NameIDEntity(195, "Senior Executive Strategic Planning"),
  NameIDEntity(196, "Senior Guide"),
  NameIDEntity(197, "Senior Human Capital Executive"),
  NameIDEntity(198, "Senior Oracle Fusion Middleware Developer"),
  NameIDEntity(199, "Senior Purchasing Executive"),
  NameIDEntity(200, "Senior Statistician"),
  NameIDEntity(201, "Senior Surveyor"),
  NameIDEntity(202, "Senior Surveyor Roads"),
  NameIDEntity(203, "Senior System Administrator"),
  NameIDEntity(204, "Senior System Engineer"),
  NameIDEntity(205, "Site Engineer"),
  NameIDEntity(206, "Statistical Data Collector"),
  NameIDEntity(207, "Structural Engineer"),
  NameIDEntity(208, "Structural Engineer-Civil"),
  NameIDEntity(209, "Supervisor of Eservice"),
  NameIDEntity(210, "Supervisor of Human Resource"),
  NameIDEntity(211, "Supervisor of Networking Security"),
  NameIDEntity(212, "Supervisor Techincal Support"),
  NameIDEntity(213, "Support Services DEPT Director"),
  NameIDEntity(214, "Surveyor"),
  NameIDEntity(215, "Technical Support Executive"),
  NameIDEntity(216, "Technical Support Officer"),
  NameIDEntity(217, "Technician"),
  NameIDEntity(218, "Tourism & Archaeology Department"),
  NameIDEntity(219, "Tourism Dept"),
  NameIDEntity(220, "Traffic Controller"),
  NameIDEntity(221, "Training & Development Expert"),
  NameIDEntity(222, "treasurer"),
  NameIDEntity(223, "Urban Planning Consultant"),
  NameIDEntity(224, "Vice President of the General Department of Health"),
];

/// ISO CR current-step filter options (id = AssignedRole sent as `currentStep` API param).
final List<NameIDEntity> isoCrCurrentStepFilters = [
  NameIDEntity(2, 'Infrastructure Director Approval'),
  NameIDEntity(3, 'System Team Implementation'),
  NameIDEntity(4, 'Oracle Team Implementation'),
  NameIDEntity(5, 'Time Attendance Team Implementation'),
  NameIDEntity(6, 'New Department'),
  NameIDEntity(7, 'Network Team Implementation'),
  NameIDEntity(8, 'System and Network Security'),
  NameIDEntity(9, 'DB Team'),
  NameIDEntity(10, 'DATABASE DIRECTOR'),
];

final crRequestReport = [
  {"key": "requestId", "Name": "Request Id"},
  {"key": "requestType", "Name": "Request Type"},
  {"key": "requestPriority", "Name": "Priority"},
  {"key": "currentStep", "Name": "Current Step"},
  {"key": "assginedEmployee", "Name": "Assgined Employee"},
  {"key": "requestStatus", "Name": "Request Status"},
  {"key": "createdAt", "Name": "Created On"},
  {"key": "updatedAt", "Name": "Updated On"},
];

final crRequestWorkflow1 = [
  {"key": "firstName", "Name": "First Name"},
  {"key": "lastName", "Name": "Last Name"},
  {"key": "fullName", "Name": "Full Name"},
  {"key": "Designation", "Name": "Designation"},
  {"key": "departmentName", "Name": "Department"},
  {"key": "reportingManager", "Name": "ReportingManager"},
  {"key": "employeeID", "Name": "EmployeeID"},
  {"key": "emailID", "Name": "Suggestive Email"},
  {"key": "dateOfJoining", "Name": "Date Of Joining"},
  {"key": "comments", "Name": "Comments"},
  {"key": "createdAt", "Name": "Created On"},
  {"key": "updatedAt", "Name": "Updated On"},
];

final crRequestWorkflow2 = [
  {"key": "firstName", "Name": "First Name"},
  {"key": "lastName", "Name": "Last Name"},
  {"key": "fullName", "Name": "Full Name"},
  {"key": "Designation", "Name": "Designation"},
  {"key": "exstingDepartmentName", "Name": "Existing Department"},
  {"key": "departmentName", "Name": "New Department"},
  {"key": "employeeID", "Name": "Employee ID"},
  {"key": "comments", "Name": "Comments"},
  {"key": "createdAt", "Name": "Created On"},
  {"key": "updatedAt", "Name": "Updated On"},
];

final crRequestWorkflow3 = [
  {"key": "firstName", "Name": "First Name"},
  {"key": "lastName", "Name": "Last Name"},
  {"key": "fullName", "Name": "Full Name"},
  {"key": "departmentName", "Name": "Department"},
  {"key": "accessType", "Name": "Access Details"},
  {"key": "reasonOfAccess", "Name": "Reason Of Access"},
  {"key": "comments", "Name": "Comments"},
  {"key": "createdAt", "Name": "Created On"},
  {"key": "updatedAt", "Name": "Updated On"},
];
